extends Node

## Run music. Autoloaded so it survives scene reloads between runs without
## restarting the track from the top.
##
## The loop is generated by tools/gen_music.py — our own work, see
## assets/CREDITS.md.

const TRACK_PATH := "res://assets/music/synthwave_loop.ogg"

## Sits well under the SFX. Gameplay audio has to stay readable — the music is
## atmosphere, not the foreground. Phase 5 exposes this as a settings slider.
const MUSIC_DB := -17.0

var _player: AudioStreamPlayer


func _ready() -> void:
	# Keeps playing through the level-up pause; silence there would feel broken.
	process_mode = Node.PROCESS_MODE_ALWAYS

	var track: AudioStream = load(TRACK_PATH)
	# Set the loop flag on the resource rather than relying on the import
	# default, so the track keeps going regardless of import settings.
	if track is AudioStreamOggVorbis:
		track.loop = true

	_player = AudioStreamPlayer.new()
	_player.stream = track
	_player.volume_db = MUSIC_DB
	add_child(_player)


## Autoloads are torn down after the resource tracker runs its check, so a
## still-referenced AudioStream is reported as "resources still in use at exit".
## Dropping the reference here keeps shutdown clean.
func _exit_tree() -> void:
	if _player != null:
		_player.stop()
		_player.stream = null


func start() -> void:
	if not _player.playing:
		_player.play()


func stop() -> void:
	_player.stop()


func set_volume_db(db: float) -> void:
	_player.volume_db = db
