extends Node

## Sound effects. Autoloaded, so any script can call Sfx.play("hit").
##
## All sounds are generated by tools/gen_sfx.py — our own work, no third-party
## licence. See assets/CREDITS.md.

const VOICES := Balance.SFX_VOICES

## Minimum gap between two plays of the SAME sound. Hundreds of enemies die in a
## run and dozens can die in one frame; without this the mix turns to mush and
## clips hard. Distinct sounds are unaffected.
const RETRIGGER_GAP := Balance.SFX_RETRIGGER_GAP

const SOUNDS := {
	"shoot": preload("res://assets/sfx/shoot.wav"),
	"hit": preload("res://assets/sfx/hit.wav"),
	"enemy_death": preload("res://assets/sfx/enemy_death.wav"),
	"xp_pickup": preload("res://assets/sfx/xp_pickup.wav"),
	"level_up": preload("res://assets/sfx/level_up.wav"),
	"player_hurt": preload("res://assets/sfx/player_hurt.wav"),
	"run_over": preload("res://assets/sfx/run_over.wav"),
	"dash": preload("res://assets/sfx/dash.wav"),
	"boss_spawn": preload("res://assets/sfx/boss_spawn.wav"),
	"boss_death": preload("res://assets/sfx/boss_death.wav"),
}

## Applied on top of each sound's mix level, driven by the settings slider.
var volume_offset_db := 0.0

var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0
var _last_played := {}
var _clock := 0.0


func _ready() -> void:
	# Audio is cosmetic; it must keep working while the tree is paused so the
	# level-up sting is not cut off by the pause it triggers.
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in VOICES:
		var voice := AudioStreamPlayer.new()
		add_child(voice)
		_voices.append(voice)


## Stop every voice and drop its stream reference. Used by the clean-quit path
## and by Phase 5's mute/settings.
##
## Note: this does NOT silence Godot's "N resources still in use at exit"
## message. That is reported for the AudioStreamWAVs held by this script's
## const preloads and by the engine's resource cache, and it scales with the
## number of audio resources loaded — it is a shutdown-order artifact, not a
## runtime leak. Verified: the count is identical whether streams are stopped
## first or not.
func stop_all() -> void:
	for voice in _voices:
		voice.stop()
		voice.stream = null


func _exit_tree() -> void:
	stop_all()


func _process(delta: float) -> void:
	_clock += delta


## volume_db defaults to the per-sound mix level in balance.gd, so call sites
## just say what happened and the mix stays tunable in one place.
## Exposed so tests can cross-check the loaded set against Balance.SFX_DB.
func sound_names() -> Array:
	return SOUNDS.keys()


func has_sound(sound_name: String) -> bool:
	return SOUNDS.has(sound_name)


func play(sound_name: String, volume_db: float = NAN) -> void:
	if is_nan(volume_db):
		volume_db = Balance.SFX_DB.get(sound_name, 0.0)
	if not SOUNDS.has(sound_name):
		push_warning("Sfx.play: unknown sound '%s'" % sound_name)
		return

	if _clock - float(_last_played.get(sound_name, -999.0)) < RETRIGGER_GAP:
		return
	_last_played[sound_name] = _clock

	var voice := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % VOICES
	voice.stream = SOUNDS[sound_name]
	voice.volume_db = volume_db + volume_offset_db
	voice.play()
