extends Node

## Sound effects. Autoloaded, so any script can call Sfx.play("hit").
##
## All sounds are generated by tools/gen_sfx.py — our own work, no third-party
## licence. See assets/CREDITS.md.

const VOICES := 16

## Minimum gap between two plays of the SAME sound. Hundreds of enemies die in a
## run and dozens can die in one frame; without this the mix turns to mush and
## clips hard. Distinct sounds are unaffected.
const RETRIGGER_GAP := 0.035

const SOUNDS := {
	"shoot": preload("res://assets/sfx/shoot.wav"),
	"hit": preload("res://assets/sfx/hit.wav"),
	"enemy_death": preload("res://assets/sfx/enemy_death.wav"),
	"xp_pickup": preload("res://assets/sfx/xp_pickup.wav"),
	"level_up": preload("res://assets/sfx/level_up.wav"),
	"player_hurt": preload("res://assets/sfx/player_hurt.wav"),
	"run_over": preload("res://assets/sfx/run_over.wav"),
}

var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0
var _last_played := {}
var _clock := 0.0


func _ready() -> void:
	# Audio is cosmetic; it must keep working while the tree is paused so the
	# level-up sting is not cut off by the pause it triggers.
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in VOICES:
		var voice := AudioStreamPlayer.new()
		add_child(voice)
		_voices.append(voice)


## See music.gd: drop stream references before the engine's exit-time resource
## check runs, otherwise shutdown reports leaked instances.
func _exit_tree() -> void:
	for voice in _voices:
		voice.stop()
		voice.stream = null


func _process(delta: float) -> void:
	_clock += delta


func play(sound_name: String, volume_db: float = 0.0) -> void:
	if not SOUNDS.has(sound_name):
		push_warning("Sfx.play: unknown sound '%s'" % sound_name)
		return

	if _clock - float(_last_played.get(sound_name, -999.0)) < RETRIGGER_GAP:
		return
	_last_played[sound_name] = _clock

	var voice := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % VOICES
	voice.stream = SOUNDS[sound_name]
	voice.volume_db = volume_db
	voice.play()
